### ISSUE TITLE
Mutable ref to self in (un)protect methods

### ISSUE THREAD

**Issue by Mnwa** [HyeonuPark/srtp#2]
Hey! It's really required to make mutable reference and the not mutable ref will be doing UB?

**Comment by HyeonuPark** [comment]
This crate is backed by the libsrtp, a C library written by the Cisco Systems, Inc. Documentation of the library doesn't mention anything about thread safety. Making it `!Sync` would be possible since the ffi function will never called recursively, but I think it only hurts usability.

Anyway, to follow the spec this crate needs to update its context whenever protect/unprotect is called, mainly counter bumps. So I think it's natural interface to satisfy the spec.

**Comment by Mnwa** [comment]
Ok. Thank you!
